const products = [
    {id: 1, name: 'Coca Cola 1L', image: 'assets/img/coca-cola-1l.jpg', price: '4.00', category: 1 },
    {id: 2, name: 'Coca Cola 2L', image: 'assets/img/g-coca-2l.jpg', price: '7.00', category: 1 },
    {id: 3, name: 'Coca Cola 3L', image: 'assets/img/coca-cola-3l.jpg', price: '12.00', category: 1 },
    {id: 4, name: 'Inca Kola 625ml', image: 'assets/img/g-inca-gordita.jpg', price: '3.00', category: 1 },
    {id: 5, name: 'Inca Kola 1L', image: 'assets/img/g-inca-1l.jpg', price: '4.00', category: 1 },
    {id: 6, name: 'Inca Kola 2L', image: 'assets/img/g-inca-2l.png', price: '12.00', category: 1 },
    {id: 7, name: 'Inca Kola 3L', image: 'assets/img/g-inca-3l.jpg', price: '12.00', category: 1 },
    {id: 8, name: 'Guaraná 3L', image: 'assets/img/g-guarana-3l.jpg', price: '10.00', category: 1 },
    {id: 9, name: 'Guaraná 350ml', image: 'assets/img/g-guarana-350ml.jpg', price: '1.00', category: 1 },
    {id: 10, name: 'Big Cola 400ml', image: 'assets/img/g-big-400ml.jpg', price: '1.00', category: 1 },
    {id: 11, name: 'Big Cola 3L', image: 'assets/img/g-big-3l.jpg', price: '8.00', category: 1 },
    {id: 12, name: 'Pepsi 3L', image: 'assets/img/g-pepsi-3l.jpg', price: '10.00', category: 1 },
    {id: 13, name: 'Kr Piña 3L', image: 'assets/img/g-kr-piña-3l.jpg', price: '10.00', category: 1 },
    {id: 14, name: 'Kr Piña 400ml', image: 'assets/img/g-kr-piña-400ml.jpg', price: '1.00', category: 1 },
    {id: 15, name: 'Kr Limón 400ml', image: 'assets/img/g-kr-limon-400ml.jpg', price: '1.00', category: 1 },
  
    {id: 16, name: 'Cerveza Cristal', image: 'assets/img/c-cristal.webp', price: '6.50', category: 2 },
    {id: 17, name: 'Cusqueña Negra', image: 'assets/img/c-negra.jpg', price: '7.00', category: 2 },
    {id: 18, name: 'Cusqueña Trigo', image: 'assets/img/c-trigo.jpg', price: '7.00', category: 2 },

    {id: 19, name: 'Agua Cielo 500ml', image: 'assets/img/a-cielo.jpg', price: '1.00', category: 3},
    {id: 20, name: 'Agua Benedictino 1L', image: 'assets/img/a-benedictino.png', price: '1.00', category: 3 },
    {id: 21, name: 'Agua San Carlos 500ml', image: 'assets/img/a-san-luis.jpg', price: '1.00', category: 3 },
    {id: 22, name: 'Agua Benedictino 3L', image: 'assets/img/a-benedictino-3l.jpg', price: '5.00', category: 3 },

    {id: 23, name: 'Yogurt Gloria Fresa 1L', image: 'assets/img/y-gloria-fresa-1l.jpg', price: '5.00', category: 4 },
    {id: 24, name: 'Yogurt Gloria Vainilla 1L', image: 'assets/img/y-gloria-vainilla-1l.jpg', price: '5.00', category: 4 },
    {id: 25, name: 'Yogurt Gloria Durazno 1L', image: 'assets/img/y-gloria-durazno-1l.jpg', price: '5.00', category: 4 },
    {id: 26, name: 'Yogurt Gloria Fresa 200ml', image: 'assets/img/y-gloria-fresa-200ml.jpg', price: '2.50', category: 4 },
    {id: 27, name: 'Yogurt Gloria Durazno 200ml', image: 'assets/img/y-gloria-durazno-200ml.jpg', price: '2.50', category: 4 },
    {id: 28, name: 'Yogurt Gloria Lucuma 200ml', image: 'assets/img/y-gloria-lucuma-200ml.jpg', price: '2.50', category: 4 },

    {id: 29, name: 'Pulp 350ml', image: 'assets/img/b-pulp-350ml.jpg', price: '1.00', category: 5 },
    {id: 30, name: 'Pulp 1L', image: 'assets/img/b-pulp-1l.jpg', price: '1.00', category: 5 },
    {id: 31, name: 'Volt 350ml', image: 'assets/img/b-volt-350ml.jpg', price: '2.50', category: 5 },
    {id: 32, name: 'Cifrut Naranja 350ml', image: 'assets/img/b-cifrut-naranja-350ml.jpg', price: '1.00', category: 5 },
    {id: 33, name: 'Cifrut Granadilla 350ml', image: 'assets/img/b-cifrut-granadilla-350ml.jpg', price: '1.00', category: 5 },
    {id: 34, name: 'Sporade 500ml', image: 'assets/img/b-sporade-500ml.jpg', price: '2.50', category: 5 },
    {id: 35, name: 'Powerade Multifrutas 600ml', image: 'assets/img/b-powerade-multifrutas-600ml.jpg', price: '2.50', category: 5,  estado: 0 },
    {id: 36, name: 'Powerade Maracuyá 600ml', image: 'assets/img/b-powerade-maracuya-600ml.jpg', price: '2.50', category: 5 },
    {id: 37, name: 'Frugos del valle 500ml', image: 'assets/img/b-del-valle-500ml.jpg', price: '2.00', category: 5 },
    {id: 38, name: 'Frugos del valle 1.5L', image: 'assets/img/b-del-valle-1.5l.jpg', price: '4.50', category: 5 },
    {id: 39, name: 'Frugos del valle 3L', image: 'assets/img/b-del-valle-3l.jpg', price: '7.50', category: 5 },

    {id: 40, name: 'Leche Gloria', image: 'assets/img/l-gloria.jpg', price: '5.00', category: 6 },
    {id: 41, name: 'Leche Ideal', image: 'assets/img/l-ideal.png', price: '3.00', category: 6 },
    {id: 42, name: 'Leche Gloria 200ml', image: 'assets/img/l-gloria-xs.jpg', price: '2.50', category: 6 },
 
    {id: 43, name: 'Ace', image: 'assets/img/d-ace.jpg', price: '5.00', category: 7 },
    {id: 44, name: 'Opal', image: 'assets/img/d-opal.jpg', price: '3.00', category: 7 },
    {id: 45, name: 'Trome', image: 'assets/img/d-trome.jpg', price: '1.50', category: 7 },
    {id: 46, name: 'Patito', image: 'assets/img/d-patito.jpg', price: '1.50', category: 7 },

    {id: 47, name: 'Aceite Primor 900ml', image: 'assets/img/dp-aceite-primor-900ml.jpg', price: '8.00', category: 8 },
    {id: 48, name: 'Aceite Primor 200ml', image: 'assets/img/dp-aceite-primor-200ml.jpg', price: '2.50', category: 8 },
    {id: 49, name: 'Cocoa Winters', image: 'assets/img/dp-cocoa-winters.jpg', price: '1.0', category: 8 },
    {id: 50, name: 'Manty', image: 'assets/img/dp-manty.jpg', price: '2.50', category: 8 },
    {id: 51, name: 'Altomayo', image: 'assets/img/dp-altomayo.jpg', price: '2.50', category: 8 },
    {id: 52, name: 'Sal Marina', image: 'assets/img/dp-sal-marina.jpg', price: '1.50', category: 8 },
    {id: 53, name: 'Ajinomen', image: 'assets/img/dp-ajinomen.jpg', price: '1.50', category: 8 },
    {id: 54, name: 'Azucar Rubia 1Kg', image: 'assets/img/dp-azucar-rubia.jpg', price: '3.50', category: 8 },
    {id: 55, name: 'Arroz  D\'Leite 1Kg', image: 'assets/img/dp-arroz-d-leite.jpg', price: '3.50', category: 8 },

    {id: 56, name: 'Papel Higiénico Noble', image: 'assets/img/h-noble.jpg', price: '1.50', category: 9 },
    {id: 57, name: 'Papel Higiénico Suave', image: 'assets/img/h-suave.jpg', price: '1.50', category: 9 },
    {id: 58, name: 'Pasta Dental Kolynos', image: 'assets/img/h-kolynos.jpg', price: '2.50', category: 9 },
    {id: 59, name: 'Pasta Dental Dento', image: 'assets/img/h-dento.jpg', price: '2.50', category: 9 },
    {id: 60, name: 'Champú head & Shoulders', image: 'assets/img/h-champu-hs.webp', price: '2.50', category: 9 },
  ];

const categories = [
    {id: 1, name: 'Gaseosas'},
    {id: 2, name: 'Cervezas'},
    {id: 3, name: 'Aguas'},
    {id: 4, name: 'Bebidas'},
    {id: 5, name: 'Yogurts'},
    {id: 6, name: 'Despensa'},
    {id: 7, name: 'Higiene'},
    {id: 8, name: 'Detergentes'},
    {id: 9, name: 'Leches'},
  ];